
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Start app HTTP server
      - run:
          name: Running app HTTP server
          command: node app/server
          background: true
        
      # run tests!
      - run: yarn test

      - store_artifacts:
          path: report.json
          prefix: tests

      - store_test_results:
          path: report.json


