
version 2
jobs
  build
    docker
      - image circlecinode7.10

    working_directory ~repo

    steps
      - checkout

      # Download and cache dependencies
      - restore_cache
          keys
          - v1-dependencies-{{ checksum package.json }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run yarn install

      - save_cache
          paths
            - node_modules
          key v1-dependencies-{{ checksum package.json }}

      # Start app HTTP server
      - run
          name Running app HTTP server
          command node app/server
          background true
        
      # run tests!
      - run yarn test


